#!/bin/sh

# Startup Background
xrdb ~/.config/X11/xresources &
xsetroot -cursor_name left_ptr &
setxkbmap be && exec sxhkd &
picom --experimental-backends --backend glx -b &
dunst &

# Custome scirpts
source $HOME/.config/env 
remaps &
dock.sh &
SPTN.sh &
MO.sh &
DFO.sh &

# Startup applicaitons
start-spotify &
alacritty --hold -e zsh -c "berserk.sh && zsh" &

# Display/Window manager
exec bspwm
