#! /bin/sh

feh --no-fehbg --bg-fill "$HOME/.config/bspwm/wallpaper"
source $HOME/.config/env

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width        0
bspc config border_radius      15
bspc config window_gap          5

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
bspc config single_monocle	 true
bspc config focused_border_color \#FEFEFE
bspc config normal_border_color \#111824

bspc config pointer_modifier control
bspc config pointer_action1 move
bspc config pointer_action2 resize_sidie

bspc config external_rules_command $HOME/.config/bspwm/external_rules.sh

bspc rule -a Alacritty desktop='^1' follow=on state=pseudo_tiled
bspc rule -a qutebrowser desktop='^2' 
bspc rule -a newsboat desktop='^4' follow=on state=pseudo_tiled
bspc rule -a Vim desktop='^5' follow=on state=pseudo_tiled
bspc rule -a Zathura desktop='^6' follow=on state=tiled
bspc rule -a Sxiv desktop='^6' follow=off 
bspc rule -a Gimp desktop='^7' state=floating 
bspc rule -a minecraft-launcher desktop='^8'
bspc rule -a discord desktop='^9' follow=off  
bspc rule -a Spotify desktop='^10' follow=off state=floating
bspc rule -a Pcmanfm state=floating
bspc rule -a mpv focus=off state=floating
bspc rule -a Screenkey manage=off
bspc rule -a scratchpad locked=on sticky=on state=floating hidden=on
bspc rule -a lf locked=on sticky=on state=floating hidden=on
bspc rule -a cool-retro-term state=pseudo_tiled

bspc desktop '^3' -l monocle
bspc desktop '^5' -l monocle

# SCRATCHPADS

sid=$(wmctrl -lx | grep scratch.scratchpad| cut -d' ' -f1| head -1) \
&& [ -z "$(echo $sid)" ] \
	&& alacritty -t scratchpad --class scratch,scratchpad -d 35 10\
	& sleep 1 \
	&& sid=$(wmctrl -lx | grep scratch.scratchpad| cut -d' ' -f1| head -1) \
	&& echo "$sid" > /tmp/scratchID ;

cid=$(wmctrl -lx | grep calc.scratchpad| cut -d' ' -f1| head -1) \
&& [ -z "$(echo $cid)" ] \
	&& alacritty -t calculator --class calc,scratchpad -d 35 10 -e bash -c "echo "" && calc -d" \
	& sleep 1 \
	&& cid=$(wmctrl -lx | grep calc.scratchpad| cut -d' ' -f1| head -1) \
	&& echo "$cid" > /tmp/calcID ;

# LF
lid=$(wmctrl -lx | grep lf.lf| cut -d' ' -f1| head -1) \
&& [ -z "$(echo $lid)" ] \
	&& alacritty --config-file .config/alacritty/lf.yml -t lf --class lf,lf -d 75 16 -e startlf \
	& sleep 1 \
	&& lid=$(wmctrl -lx | grep lf.lf| cut -d' ' -f1| head -1) \
	&& echo "$lid" > /tmp/lfID;

# Because spotify won't listen
setsid -f start-spotify > /dev/null 2>&1 &
