#! /bin/sh

xwallpaper --zoom "$HOME/.config/bspwm/wallpaper"
source $HOME/.config/env

bspc monitor eDP-1 -d I II III IV V VI VII VIII IX X
bspc monitor DP-1 -d I II III IV V VI VII VIII IX X

bspc config border_width        	0
bspc config window_gap          	5

bspc config split_ratio          	0.52
bspc config borderless_monocle   	true
bspc config gapless_monocle      	true
bspc config focus_follows_pointer 	true
bspc config pointer_follows_focus 	true
bspc config single_monocle	 	true
bspc config initial_polarity 		first_child
bspc config automatic_scheme 		spiral

bspc config pointer_modifier 		control
bspc config pointer_action1 		move
bspc config pointer_action2 		resize_sidie

bspc config external_rules_command $HOME/.config/bspwm/external_rules.sh

bspc rule -a Alacritty desktop='^1' follow=on state=pseudo_tiled
bspc rule -a qutebrowser desktop='^2' 
bspc rule -a Chromium desktop='^2' 
bspc rule -a Vim desktop='^3' follow=on 
bspc rule -a Emacs desktop='^3' follow=on state=tiled
bspc rule -a DrRacket desktop='^3' follow=off 
bspc rule -a Zathura desktop='^4' follow=on state=tiled
bspc rule -a Nsxiv desktop='^4' follow=on 
bspc rule -a newsboat desktop='^6' follow=on state=pseudo_tiled
bspc rule -a Gimp desktop='^7' state=floating 
bspc rule -a Racket desktop='^8' follow=on state=pseudo_tiled
bspc rule -a discord desktop='^9' follow=off state=pseudo_tiled rectangle=1650x900+200+80

bspc rule -a mpv focus=off state=floating
bspc rule -a scratchpad rectangle=750x465+20+540 locked=on sticky=on state=floating hidden=on
bspc rule -a gotop locked=on sticky=on state=floating
bspc rule -a lf rectangle=960x460+10+550 locked=on sticky=on state=floating hidden=on
bspc rule -a qb-lf locked=on state=floating 

bspc rule -a Surf state=tiled
bspc rule -a Dragon-drag-and-drop locked=on sticky=on 
bspc rule -a cool-retro-term state=pseudo_tiled

bspc desktop '^5' -l monocle

# SCRATCHPAD

sid=$(wmctrl -lx | grep scratch.scratchpad| cut -d' ' -f1| head -1) \
&& [ -z "$(echo $sid)" ] \
	&& alacritty -t scratchpad --class scratch,scratchpad -e zsh -c "macchina; zsh"\
	& sleep 1 \
	&& sid=$(wmctrl -lx | grep scratch.scratchpad| cut -d' ' -f1| head -1) \
	&& echo "$sid" > /tmp/scratchID ;

# LF
lid=$(wmctrl -lx | grep lf.lf| cut -d' ' -f1| head -1) \
&& [ -z "$(echo $lid)" ] \
	&& alacritty --config-file .config/alacritty/lf.yml -t lf --class lf,lf -e lf-ueberzug \
	& sleep 1 \
	&& lid=$(wmctrl -lx | grep lf.lf| cut -d' ' -f1| head -1) \
	&& echo "$lid" > /tmp/lfID;
