#! /bin/sh

xwallpaper --zoom "$HOME/.config/bspwm/wallpaper"
source $HOME/.config/env

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width        	0
bspc config window_gap          	5

bspc config split_ratio          	0.52
bspc config borderless_monocle   	true
bspc config gapless_monocle      	true
bspc config focus_follows_pointer 	true
bspc config pointer_follows_focus 	true
bspc config single_monocle	 	true
bspc config initial_polarity 		first_child
bspc config automatic_scheme 		longest_side

bspc config pointer_modifier 		control
bspc config pointer_action1 		move
bspc config pointer_action2 		resize_sidie

bspc config external_rules_command $HOME/.config/bspwm/external_rules.sh

bspc rule -a Alacritty desktop='^1' follow=on state=pseudo_tiled
bspc rule -a qutebrowser desktop='^2' 
bspc rule -a Chromium desktop='^2' 
bspc rule -a newsboat desktop='^4' follow=on state=pseudo_tiled
bspc rule -a Vim desktop='^5' follow=on 
bspc rule -a Emacs desktop='^5' follow=on state=tiled
bspc rule -a DrRacket desktop='^5' follow=off 
bspc rule -a Zathura desktop='^6' follow=on state=pseudo_tiled
bspc rule -a Sxiv desktop='^6' follow=off 
bspc rule -a Gimp desktop='^7' state=floating 
bspc rule -a discord desktop='^9' follow=off  

bspc rule -a mpv focus=off state=floating
bspc rule -a scratchpad rectangle=550x310+10+700 locked=on sticky=on state=floating hidden=on
bspc rule -a lf rectangle=960x460+10+550 locked=on sticky=on state=floating hidden=on

bspc rule -a Surf state=pseudo_tiled
bspc rule -a Dragon-drag-and-drop locked=on sticky=on 
bspc rule -a cool-retro-term state=pseudo_tiled

bspc desktop '^3' -l monocle

# SCRATCHPAD

sid=$(wmctrl -lx | grep scratch.scratchpad| cut -d' ' -f1| head -1) \
&& [ -z "$(echo $sid)" ] \
	&& alacritty -t scratchpad --class scratch,scratchpad \
	& sleep 1 \
	&& sid=$(wmctrl -lx | grep scratch.scratchpad| cut -d' ' -f1| head -1) \
	&& echo "$sid" > /tmp/scratchID ;

# LF
lid=$(wmctrl -lx | grep lf.lf| cut -d' ' -f1| head -1) \
&& [ -z "$(echo $lid)" ] \
	&& alacritty --config-file .config/alacritty/lf.yml -t lf --class lf,lf -e lf-ueberzug \
	& sleep 1 \
	&& lid=$(wmctrl -lx | grep lf.lf| cut -d' ' -f1| head -1) \
	&& echo "$lid" > /tmp/lfID;
